#!/usr/bin/env bash

if [ ! -z "$USERNAME" ]; then
    usermod -u $USERNAME www-data
fi

# if [ $# -gt 0 ]; then
#     exec su-exec $USERNAME "$@"
# else
#     /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
# fi
